# Google Cloud Build 設定ファイル
# Cloud Runへの自動デプロイ用

steps:
  # 1. Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/voicenote-audio-processor:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/voicenote-audio-processor:latest'
      - '.'

  # 2. Container Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/voicenote-audio-processor:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/voicenote-audio-processor:latest'

  # 3. Cloud Run にデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'voicenote-audio-processor'
      - '--image'
      - 'gcr.io/$PROJECT_ID/voicenote-audio-processor:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '8Gi'
      - '--cpu'
      - '4'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,ENVIRONMENT=production'

# ビルドオプション
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'
  logging: 'CLOUD_LOGGING_ONLY'

# ビルド成果物
images:
  - 'gcr.io/$PROJECT_ID/voicenote-audio-processor:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/voicenote-audio-processor:latest'

# ビルド時間制限
timeout: '3600s'

# 置換変数
substitutions:
  _SERVICE_NAME: 'voicenote-audio-processor'
  _REGION: 'asia-northeast1'